replicaCount: 2

fullnameOverride: drug-catalog-service

image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/drug-catalog-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082

ingress:
  enabled: false
  className: nginx
  host: pharma.internal
  path: /catalog
  pathType: Prefix

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

livenessProbe:
  path: /actuator/health
  port: 8082
  initialDelaySeconds: 90
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  path: /actuator/health/readiness
  port: 8082
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

configmap:
  SPRING_PROFILES_ACTIVE: prod
  DB_HOST: <RDS_ENDPOINT>
  LOG_LEVEL: WARN
  SERVER_PORT: "8082"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"

envFrom:
  - secretRef:
      name: db-credentials

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - drug-catalog-service
        topologyKey: kubernetes.io/hostname

serviceAccount:
  create: true
  annotations: {}
  name: drug-catalog-service
